_BASE_: boxvis_R50_bs16.yaml
MODEL:
  WEIGHTS: 'pretrained/boxvis_R50.pth'
  BoxVIS:
    TEST:
      WINDOW_INFERENCE: True
DATASETS:
  TEST: ("ovis_dev", )
INPUT:
  MIN_SIZE_TEST: 480
OUTPUT_DIR: output/bvisd/boxvis_r50_bs16_test_ovis/
