_BASE_: boxvis_swinl_bs8.yaml
MODEL:
  WEIGHTS: 'pretrained/boxvis_swinl.pth'
  BoxVIS:
    TEST:
      WINDOW_INFERENCE: True
      TRACKER_TYPE: 'mdqe'
      MERGE_ON_CPU: False  # if out of memory, set True
      NUM_FRAMES_WINDOW: 30  # 15 if GPUs have 24G memory
DATASETS:
  TEST: ("ovis_dev", )
INPUT:
  MIN_SIZE_TEST: 480
OUTPUT_DIR: output/bvisd/boxvis_swinl_bs8_test_ovis/
