_BASE_: Base-BoxVIS.yaml
MODEL:
  WEIGHTS: "pretrained/model_final_3c8ec9.pkl"
  META_ARCHITECTURE: "BoxVIS_VideoMaskFormer"
DATASETS:
  DATASET_RATIO: [2., 1., 1.]
  TRAIN: ("ytvis_2021_train", "ovis_train", "coco2bvisd_train")
  TEST: ("bvisd_dev", )
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.0001
  STEPS: (12000,)
  MAX_ITER: 15000
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 10
  WEIGHT_DECAY: 0.05
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
  CHECKPOINT_PERIOD: 2000
INPUT:
  SAMPLING_FRAME_NUM: 3
  SAMPLING_FRAME_RANGE: 10
  SAMPLING_FRAME_SHUFFLE: False
  # MIN_SIZE_TRAIN_SAMPLING : ["range", "choice", "range_by_clip", "choice_by_clip"]
  MIN_SIZE_TRAIN_SAMPLING: "choice_by_clip"
  # RANDOM_FLIP : ["none", "horizontal", "flip_by_clip"]. "horizontal" is set by default.
  RANDOM_FLIP: "flip_by_clip"
  AUGMENTATIONS: []
  MIN_SIZE_TRAIN: (320, 352, 384, 416, 448, 480, 512)
  MAX_SIZE_TRAIN: 800
  MIN_SIZE_TEST: 360
  FORMAT: "RGB"
  CROP:
    ENABLED: False
    TYPE: "absolute_range"
    SIZE: (384, 600)
  # For pseudo videos
  PSEUDO:
    AUGMENTATIONS: ['rotation']
    MIN_SIZE_TRAIN: (320, 352, 384, 416, 448, 480, 512)
    MAX_SIZE_TRAIN: 800
    CROP:
      ENABLED: True
      TYPE: "absolute_range"
      SIZE: (320, 480)
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 4
TEST:
  EVAL_PERIOD: 2000
OUTPUT_DIR: output/bvisd/boxvis_r50_bs16/
